Use getopts for commandline parsing in cmd and guest

diff --git a/lib/ioh-guest b/lib/ioh-guest
--- a/lib/ioh-guest
+++ b/lib/ioh-guest
@@ -2,7 +2,20 @@
 
 # List Guests
 __list() {
-	local flags="$1"
+	#local flags="$1"
+	local flags
+	while getopts l c; do
+		case $c in
+			l)
+				flags="-l"
+				;;
+			\?)
+				echo "Invalid argument: $c"
+				exit 1
+				;;
+		esac
+	done
+
 	local pools="$(zfs list -H | grep iohyve | cut -d '/' -f 1 | uniq )"
 	(
 	printf "%s^%s^%s^%s^%s\n" "Guest" "VMM?" "Running" "rcboot?" "Description"
@@ -45,7 +58,28 @@ __list() {
 
 # Display info about all guests.
 __info() {
-	local flags="$1"
+	shift 1
+	local verbose=false
+	local stats=false
+	local desc=false
+
+	while getopts vsd c; do
+		case $c in
+			v)
+				verbose=true
+				;;
+			s)
+				stats=true
+				;;
+			d)
+				desc=true
+				;;
+			\?)
+				echo "Invalid argument: $c"
+				exit 1
+				;;
+		esac
+	done
 
 	# Poll to see what pools have active guests
 	local pools="$(zfs list -H | grep iohyve | cut -d '/' -f 1 | uniq )"
@@ -55,17 +89,17 @@ __info() {
 	printf "%s^%s^%s^%s^%s" "Guest" "Size" "CPU" "RAM" "Pool"
 
 	# Print headers for -v flag
-	if [ -n "$(echo "$flags" | grep 'v')" ]; then
+	if $verbose; then
 		printf "^%s^%s^%s^%s" "OS" "Loader" "Tap" "Con"
 	fi
 
 	# Print headers for -s flag
-	if [ -n "$(echo "$flags" | grep 's')" ]; then
+	if $stats; then
 		printf "^%s^%s^%s" "VMM?" "Running" "rcboot?"
 	fi
 
 	# Print headers for -d flag
-	if [ -n "$(echo "$flags" | grep 'd')" ]; then
+	if $desc; then
 		printf "^%s" "Description"
 	fi
 
@@ -88,7 +122,7 @@ __info() {
 			printf "%s^%s^%s^%s^%s" "$g" "$size" "$cpu" "$ram" "$pool"
 
 			# Get variable and print for verbose section (os, loader, tap, con)
-			if [ -n "$(echo "$flags" | grep 'v')" ]; then
+			if $verbose; then
 				local os="$(zfs get -H -o value iohyve:os $pool/iohyve/$g)"
 				local loader="$(zfs get -H -o value iohyve:loader $pool/iohyve/$g)"
 				local tap="$(zfs get -H -o value iohyve:tap $pool/iohyve/$g)"
@@ -98,7 +132,7 @@ __info() {
 			fi
 
 			# Get info, set variables, and print for status section (VMM, Running, rcboot)
-			if [ -n "$(echo "$flags" | grep 's')" ] && [ -z "$(echo "$g" | grep 'disk')" ]; then
+			if $stats && [ -z "$(echo "$g" | grep 'disk')" ]; then
 				local vmm="/dev/vmm/ioh-$g"
 				if [ -e $vmm ]; then
 					vmm="YES"
@@ -120,12 +154,12 @@ __info() {
 
 				printf "^%s^%s^%s" "$vmm" "$running" "$boot"
 			# Checks to see if disk portion of guest and uses "-"s if so for this section.
-			elif [ -n "$(echo "$flags" | grep 's')" ] && [ -n "$(echo "$g" | grep 'disk')" ]; then
+			elif $stats && [ -n "$(echo "$g" | grep 'disk')" ]; then
 				printf "^-^-^-"
 			fi
 
 			# Print description if flag set
-			if [ -n "$(echo "$flags" | grep 'd')" ]; then
+			if $desc; then
 				local description="$(zfs get -H -o value iohyve:description $pool/iohyve/$g)"
 				printf "^%s" "$description"
 			fi
@@ -430,8 +464,29 @@ __prepare_guest() {
 
 # Start guest (combine load and boot)
 __start() {
+	shift 1
+	local sflag=false
+	local aflag=false
+	while getopts sa c; do
+		case $c in
+			s)
+				sflag=true
+				;;
+			a)
+				aflag=true
+				;;
+			\?)
+				echo "Invalid argument: $c"
+				exit 1
+				;;
+		esac
+	done
+
+	if $sflag && $aflag; then
+		echo "Only one flag allowed"
+		exit 1
+	fi
 	local name="$2"
-	local flag="$3"
 	local pci=""
 	local runmode="1"
 	local pool="$(zfs list -H -t volume -o name | grep iohyve/$name | grep disk0 | cut -d '/' -f1)"
@@ -446,14 +501,13 @@ __start() {
 		# Check to make sure guest isn't running
 		local running=$(pgrep -fx "bhyve: ioh-$name")
 		if [ -z $running ]; then
-			case "$flag" in
-				-s)	runmode="0"	# single - start only once
-					;;
-				-a) 	runmode="2"	# always - persist regardless what
-					;;
-				*)	runmode="1"	# persist - persists until guest is powering off
-					;;
-			esac
+			if $sflag; then
+				runmode="0"
+			elif $aflag; then
+				runmode="2"
+			else
+				runmode="1"
+			fi
 			echo "Starting $name... (Takes 15 seconds for FreeBSD guests)"
 			# Prepare and boot guest
 			pci="$(__prepare_guest $name)"
